# AVISO: Qualquer mudança feita neste arquivo será perdida quando o pyuic5 for executado novamente.
# Não edite este arquivo a menos que você saiba o que está fazendo.
# Arquivo convertido em ui2py.vercel.app

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaMenu(object):
    def setupUi(self, TelaMenu):
        TelaMenu.setObjectName("TelaMenu")
        TelaMenu.resize(699, 784)
        TelaMenu.setStyleSheet("background-color: rgb(201, 253, 255);")
        self.centralwidget = QtWidgets.QWidget(TelaMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.label_pytasks = QtWidgets.QLabel(self.centralwidget)
        self.label_pytasks.setGeometry(QtCore.QRect(220, 0, 251, 41))
        self.label_pytasks.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_pytasks.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pytasks.setObjectName("label_pytasks")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 320, 501, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_pendentes = QtWidgets.QWidget()
        self.tab_pendentes.setObjectName("tab_pendentes")
        self.tabWidget.addTab(self.tab_pendentes, "")
        self.tab_concluidas = QtWidgets.QWidget()
        self.tab_concluidas.setObjectName("tab_concluidas")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_concluidas)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 511, 411))
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_concluidas, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(530, 630, 160, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_nova_tarefa = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_nova_tarefa.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mais.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_nova_tarefa.setIcon(icon)
        self.pushButton_nova_tarefa.setIconSize(QtCore.QSize(13, 13))
        self.pushButton_nova_tarefa.setAutoExclusive(False)
        self.pushButton_nova_tarefa.setObjectName("pushButton_nova_tarefa")
        
        self.pushButton_nova_tarefa.clicked.connect(self.nova_tarefa)
        
        self.verticalLayout.addWidget(self.pushButton_nova_tarefa)
        self.pushButton_alterar_tarefa = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_alterar_tarefa.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("lapis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_alterar_tarefa.setIcon(icon1)
        self.pushButton_alterar_tarefa.setIconSize(QtCore.QSize(13, 13))
        self.pushButton_alterar_tarefa.setObjectName("pushButton_alterar_tarefa")
        
        self.pushButton_alterar_tarefa.clicked.connect(self.editar_tarefa)
        
        self.verticalLayout.addWidget(self.pushButton_alterar_tarefa)
        self.pushButton_excluir_tarefa = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_excluir_tarefa.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("lixo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_excluir_tarefa.setIcon(icon2)
        self.pushButton_excluir_tarefa.setIconSize(QtCore.QSize(13, 13))
        self.pushButton_excluir_tarefa.setObjectName("pushButton_excluir_tarefa")
        self.verticalLayout.addWidget(self.pushButton_excluir_tarefa)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(2, 342, 511, 421))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        TelaMenu.setCentralWidget(self.centralwidget)
        self.actionEditar_tarefa = QtWidgets.QAction(TelaMenu)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/tmp/UPLOADS/edit_5953096.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditar_tarefa.setIcon(icon3)
        self.actionEditar_tarefa.setObjectName("actionEditar_tarefa")
        self.actionSair = QtWidgets.QAction(TelaMenu)
        self.actionSair.setObjectName("actionSair")
        self.actionSair_2 = QtWidgets.QAction(TelaMenu)
        self.actionSair_2.setObjectName("actionSair_2")
        self.actionCTRL_N = QtWidgets.QAction(TelaMenu)
        self.actionCTRL_N.setObjectName("actionCTRL_N")
        self.actionNova_tarefa = QtWidgets.QAction(TelaMenu)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/tmp/UPLOADS/paper_14910408.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNova_tarefa.setIcon(icon4)
        self.actionNova_tarefa.setObjectName("actionNova_tarefa")

        self.retranslateUi(TelaMenu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TelaMenu)

    def retranslateUi(self, TelaMenu):
        _translate = QtCore.QCoreApplication.translate
        TelaMenu.setWindowTitle(_translate("TelaMenu", "MENU"))
        self.label_pytasks.setText(_translate("TelaMenu", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#5555ff;\">PyTasks</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pendentes), _translate("TelaMenu", "Tarefas Pendentes"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("TelaMenu", "Nome do Evento"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("TelaMenu", "Data do Evento"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("TelaMenu", "Prioridade"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("TelaMenu", "Observações"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("TelaMenu", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_concluidas), _translate("TelaMenu", "Tarefas Concluídas"))
        self.pushButton_nova_tarefa.setText(_translate("TelaMenu", "Adicionar Tarefa"))
        self.pushButton_alterar_tarefa.setText(_translate("TelaMenu", "Alterar Tarefa"))
        self.pushButton_excluir_tarefa.setText(_translate("TelaMenu", "Excluir Tarefa"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TelaMenu", "Nome do Evento"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TelaMenu", "Data do Evento"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TelaMenu", "Prioridade"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TelaMenu", "Observações"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TelaMenu", "Status"))
        
        
    def nova_tarefa(self):
        from nova_tarefa import Ui_Tela_Nova_Tarefa
        self.tela = QtWidgets.QMainWindow()
        self.cad = Ui_Tela_Nova_Tarefa()
        self.cad.setupUi(self.tela)
        self.tela.show()
        
    def editar_tarefa(self):
        from edicao_tarefa import Ui_Edicao_tarefa
        self.tela_edicao = QtWidgets.QMainWindow()
        self.ed = Ui_Edicao_tarefa()
        self.ed.setupUi(self.tela_edicao)
        self.tela_edicao.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaMenu = QtWidgets.QMainWindow()
    ui = Ui_TelaMenu()
    ui.setupUi(TelaMenu)
    TelaMenu.show()
    sys.exit(app.exec_())
