from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Nova_Tarefa(object):
    def setupUi(self, Tela_Nova_Tarefa):
        Tela_Nova_Tarefa.setObjectName("Tela_Nova_Tarefa")
        Tela_Nova_Tarefa.resize(383, 460)
        Tela_Nova_Tarefa.setMinimumSize(QtCore.QSize(383, 392))
        Tela_Nova_Tarefa.setMaximumSize(QtCore.QSize(383, 460))
        self.centralwidget = QtWidgets.QWidget(Tela_Nova_Tarefa)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_nome_tarefa = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_nome_tarefa.setObjectName("label_nome_tarefa")
        self.gridLayout.addWidget(self.label_nome_tarefa, 0, 0, 1, 1)
        self.lineEdit_nome_tarefa = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_nome_tarefa.setObjectName("lineEdit_nome_tarefa")
        self.gridLayout.addWidget(self.lineEdit_nome_tarefa, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 221, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_prioridade = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_prioridade.setObjectName("label_prioridade")
        self.gridLayout_2.addWidget(self.label_prioridade, 0, 0, 1, 1)
        self.comboBox_prioridade = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_prioridade.setObjectName("comboBox_prioridade")
        self.comboBox_prioridade.addItem("")
        self.comboBox_prioridade.addItem("")
        self.comboBox_prioridade.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_prioridade, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 60, 361, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 80, 168, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_data_evento = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_data_evento.setObjectName("label_data_evento")
        self.gridLayout_3.addWidget(self.label_data_evento, 0, 0, 1, 1)
        self.dateEdit_evento = QtWidgets.QDateEdit(self.gridLayoutWidget_3)
        self.dateEdit_evento.setObjectName("dateEdit_evento")
        self.gridLayout_3.addWidget(self.dateEdit_evento, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 160, 361, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 260, 361, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 280, 291, 91))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEdit_observacoes = QtWidgets.QTextEdit(self.gridLayoutWidget_4)
        self.textEdit_observacoes.setObjectName("textEdit_observacoes")
        self.gridLayout_4.addWidget(self.textEdit_observacoes, 0, 1, 1, 1)
        self.label_obs = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_obs.setObjectName("label_obs")
        self.gridLayout_4.addWidget(self.label_obs, 0, 0, 1, 1)
        self.pushButton_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_salvar.setGeometry(QtCore.QRect(124, 402, 151, 31))
        self.pushButton_salvar.setObjectName("pushButton_salvar")
        Tela_Nova_Tarefa.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tela_Nova_Tarefa)
        QtCore.QMetaObject.connectSlotsByName(Tela_Nova_Tarefa)

    def retranslateUi(self, Tela_Nova_Tarefa):
        _translate = QtCore.QCoreApplication.translate
        Tela_Nova_Tarefa.setWindowTitle(_translate("Tela_Nova_Tarefa", "Nova Tarefa"))
        self.label_nome_tarefa.setText(_translate("Tela_Nova_Tarefa", "Nome do Evento:"))
        self.label_prioridade.setText(_translate("Tela_Nova_Tarefa", "Prioridade do evento:"))
        self.comboBox_prioridade.setItemText(0, _translate("Tela_Nova_Tarefa", "1 - Baixa"))
        self.comboBox_prioridade.setItemText(1, _translate("Tela_Nova_Tarefa", "2 - Média"))
        self.comboBox_prioridade.setItemText(2, _translate("Tela_Nova_Tarefa", "3 - Alta"))
        self.label_data_evento.setText(_translate("Tela_Nova_Tarefa", "Data do evento:"))
        self.label_obs.setText(_translate("Tela_Nova_Tarefa", "Observações:"))
        self.pushButton_salvar.setText(_translate("Tela_Nova_Tarefa", "Salvar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tela_Nova_Tarefa = QtWidgets.QMainWindow()
    ui = Ui_Tela_Nova_Tarefa()
    ui.setupUi(Tela_Nova_Tarefa)
    Tela_Nova_Tarefa.show()
    sys.exit(app.exec_())